version: '3'

services:
  esmartofficejv:
    container_name: prod-esmartofficejv
    build: .
    image: prod-esmartofficejv:251202
    restart: unless-stopped
    volumes:
    - ./media:/app/media:rw
    env_file:
      - .env
    ports:
      - "8000:8000"
networks:
  default:
    external: true
    name: public_dnetwork