# Generated by Django 5.1.4 on 2026-05-31 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_rename_branch_id_department_department_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('employee_id', models.CharField(max_length=20, verbose_name='รหัสพนักงาน')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('prefix', models.CharField(choices=[('mr', 'นาย/Mr.'), ('mrs', 'นาง/Mrs.'), ('miss', 'นางสาว/Miss'), ('dr_m', 'น.สพ./Dr.'), ('dr_f', 'สพ.ญ./Dr.'), ('other', 'อื่นๆ')], max_length=20, verbose_name='คำนำหน้าชื่อ')),
                ('prefix_other', models.CharField(blank=True, max_length=100, null=True, verbose_name='คำนำหน้าชื่อ (อื่นๆ)')),
                ('prefix_th', models.CharField(blank=True, max_length=20, null=True, verbose_name='คำนำหน้า (ไทย)')),
                ('prefix_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='คำนำหน้า (อังกฤษ)')),
                ('firstname_th', models.CharField(default='', max_length=150, verbose_name='ชื่อ (ไทย)')),
                ('lastname_th', models.CharField(default='', max_length=150, verbose_name='นามสกุล (ไทย)')),
                ('firstname_en', models.CharField(default='', max_length=150, verbose_name='ชื่อ (อังกฤษ)')),
                ('lastname_en', models.CharField(default='', max_length=150, verbose_name='นามสกุล (อังกฤษ)')),
                ('access_level', models.CharField(choices=[('read', 'Read Only (ดูอย่างเดียว)'), ('editor', 'Editor (แก้ไขข้อมูลได้)'), ('admin', 'Admin (ผู้ดูแลระบบ)')], default='read', max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending_manager', 'รอหัวหน้าอนุมัติ (Wait for Manager)'), ('pending_it', 'รอ IT อนุมัติ (Wait for IT)'), ('approved', 'อนุมัติแล้ว (Approved)'), ('rejected', 'ไม่อนุมัติ (Rejected)')], default='pending_manager', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_approval_date', models.DateTimeField(blank=True, null=True)),
                ('manager_comment', models.TextField(blank=True, null=True, verbose_name='ความเห็น Manager')),
                ('it_approval_date', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ปฏิเสธ')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ปฏิเสธ')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='แผนก')),
                ('it_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_approvals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ (IT)')),
                ('manager_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approvals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ (Manager)')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ปฏิเสธ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_requests.position', verbose_name='ตำแหน่ง')),
                ('systems', models.ManyToManyField(to='access_requests.system')),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='การกระทำ')),
                ('details', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='access_requests.accessrequest')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ดำเนินการ')),
            ],
        ),
    ]
