# Generated by Django 5.1.4 on 2026-05-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='access_level',
        ),
    ]
