# Generated by Django 5.1.4 on 2025-05-20 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubBranch',
            fields=[
                ('sub_branch_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255, unique=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
            ],
            options={
                'db_table': 'base_sub_branch',
            },
        ),
    ]
