# Generated by Django 5.1.4 on 2025-05-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subbranch',
            old_name='branch_name',
            new_name='sub_branch_name',
        ),
    ]
