# Generated by Django 5.1.4 on 2025-05-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_branch', '0002_rename_branch_name_subbranch_sub_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbranch',
            name='sub_branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
