# Generated by Django 5.1.4 on 2024-12-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('department', '0002_rename_branch_id_department_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
