# Generated by Django 5.1.4 on 2026-05-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseimage',
            name='case_image',
            field=models.FileField(blank=True, upload_to='caseGallery'),
        ),
    ]
