# Generated by Django 5.1.4 on 2024-12-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('category', '0001_initial'),
        ('department', '0001_initial'),
        ('priority', '0001_initial'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('case_detail', models.TextField()),
                ('place_detail', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('computer_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='blogImages')),
                ('create_username', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assign_name', models.CharField(blank=True, max_length=255)),
                ('cancel_name', models.CharField(blank=True, max_length=255)),
                ('update_note', models.TextField(blank=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('modify_username', models.CharField(blank=True, max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priority.priority')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='status.status')),
            ],
            options={
                'db_table': 'case_list',
            },
        ),
    ]
