# Generated by Django 5.1.4 on 2024-12-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='place_detail',
            new_name='subject_detail',
        ),
    ]
