# Generated by Django 5.1.4 on 2024-12-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_rename_place_detail_case_subject_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
