# Generated by Django 5.1.4 on 2024-12-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_case_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
