# Generated by Django 5.1.4 on 2025-01-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_case_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='complete_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_detail',
            field=models.TextField(blank=True),
        ),
    ]
