# Generated by Django 5.1.4 on 2025-01-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_alter_case_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='receive_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='case',
            name='complete_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
