# Generated by Django 5.1.4 on 2025-01-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_alter_case_complete_date_alter_case_receive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cancel_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
