# Generated by Django 5.1.4 on 2025-01-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_case_cancel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='modify_date',
            field=models.DateTimeField(),
        ),
    ]
