# Generated by Django 5.1.4 on 2025-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_alter_case_date_created_alter_case_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
