# Generated by Django 5.1.4 on 2025-02-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_case_feedback_case_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='feedback',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
