# Generated by Django 5.1.4 on 2025-02-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_alter_case_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
