# Generated by Django 5.1.4 on 2025-02-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0015_rename_cancel_date_case_satisfied_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='cancel_name',
            new_name='satisfied_name',
        ),
    ]
