# Generated by Django 5.1.4 on 2025-02-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0016_rename_cancel_name_case_satisfied_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogImages'),
        ),
    ]
