# Generated by Django 5.1.4 on 2025-05-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0019_alter_case_category_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cancel_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='cancel_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
