# Generated by Django 5.1.4 on 2025-05-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0022_alter_case_sub_category'),
        ('sub_category', '0002_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='sub_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_category.subcategory'),
        ),
    ]
