# Generated by Django 5.1.4 on 2025-05-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0024_alter_case_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
