# Generated by Django 5.1.4 on 2025-05-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0025_case_ticket_number'),
        ('sub_branch', '0002_rename_branch_name_subbranch_sub_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='sub_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sub_branch.subbranch'),
        ),
    ]
