# Generated by Django 5.1.4 on 2025-05-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0026_case_sub_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='product_receive_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
