# Generated by Django 5.1.4 on 2025-05-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0027_case_product_receive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='product_receive_date',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
