# Generated by Django 5.1.4 on 2025-06-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0028_alter_case_product_receive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='product_receive_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
