# Generated by Django 5.1.4 on 2025-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0029_alter_case_product_receive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
