# Generated by Django 5.1.4 on 2025-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0031_alter_case_assign_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assign_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
