# Generated by Django 5.1.4 on 2025-09-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0034_alter_case_assign_name'),
        ('sub_branch', '0003_alter_subbranch_sub_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='sub_branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sub_branch.subbranch'),
        ),
    ]
