# Generated by Django 5.1.4 on 2025-10-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0035_alter_case_sub_branch'),
        ('second_sub_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='second_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='second_sub_category.secondsubcategory'),
        ),
    ]
