# Generated by Django 5.1.4 on 2026-05-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0036_case_second_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='create_username',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_created',
            field=models.DateTimeField(db_index=True),
        ),
    ]
