# Generated by Django 5.1.4 on 2026-05-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0037_alter_case_create_username_alter_case_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blogImages'),
        ),
    ]
