# Generated by Django 5.1.4 on 2026-07-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0038_alter_case_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='fa_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='เลข FA'),
        ),
    ]
