"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ukr!$@r8+widv(k9g(ud-r*%ojtj+fy_=od3^jb6=-3lt4##2p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'members',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'branch',
    'category',
    'status',
    'case',
    'loginsystem',
    'django.contrib.humanize',
    'report',
    'usermanage',
    'case_image',
    'priority',
    'department',
    'sub_category'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# MySQL
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'db_repairsystem',
#         'USER':'root',
#         'PASSWORD':'',
#         'HOST': '127.0.0.1',  # Use 'localhost' or '127.0.0.1'
#         'PORT': '3308',  # Default MySQL port
#         'OPTIONS': {
#             'sql_mode': 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION',
#         },
#     }   
# }

# Postgresql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'imedx_tlp_new',
        'USER':'eservices',
        'PASSWORD':'Tlp@2023',
        'HOST': '192.168.98.254', 
        'PORT': '5434',
        'OPTIONS': {
            'options': '-c search_path=intra_tl'
        },
    }   
}


ALLOWED_HOSTS = ['*']

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Production
# STATIC_URL = '/static/'
# STATIC_ROOT = '/app/static/'
# MEDIA_URL = '/media/'
# MEDIA_ROOT = '/app/media/'

# UAT
STATIC_URL = 'static/'
STATIC_ROOT = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = 'media/'


# MEDIA_URL = '/media/' #ระบุ path ที่เก็บไฟล์รูป
# MEDIA_ROOT = os.path.join(BASE_DIR,'media/') #ระบุ path ที่เก็บไฟล์รูปใน server

# Session Settings
# ตั้งเวลา session หมดอายุเมื่อปิดแท็บ
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# อายุของ session cookie (60 วินาที)
# SESSION_COOKIE_AGE = 1800

# คุกกี้ session จะหมดอายุหลังจากปิดเบราว์เซอร์
SESSION_COOKIE_NAME = "sessionid"

# # เปิดใช้งาน HTTPS-Related Security Settings
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# # บังคับให้เชื่อมต่อ HTTPS
# SECURE_SSL_REDIRECT = True

# # เปิดใช้งาน Strict Transport Security (HSTS)
# SECURE_HSTS_SECONDS = 31536000  # 1 ปี
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# # ใช้ Secure Cookies
SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = [
    'https://uat-ticket-jv.thonglorpet.com',  # Domain ที่คุณใช้งาน
    'http://localhost:82',  # เพิ่ม localhost ถ้าใช้งานในเครื่องพัฒนา
]

# กำหนด engine สำหรับการเก็บ session
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'members.Members'




