# Generated by Django 5.1.4 on 2026-06-09 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masterasset',
            name='asset_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='กลุ่มทรัพย์สิน'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='asset_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ประเภททรัพย์สิน'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ยี่ห้อ'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='บริษัท'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ฝ่าย'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='emp_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสพนักงาน'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='emp_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อผู้ใช้งาน'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='location_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สถานที่ตั้ง'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รุ่น'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่ PO'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='S/N'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='spec_details',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด/Spec'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ผู้ขาย'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='warranty_expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันหมดประกัน'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='asset_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='รหัสทรัพย์สิน'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets_system.assetcategory', verbose_name='หมวดหมู่ระบบ'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ถือครองในระบบ'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets_system.assetlocation', verbose_name='สถานที่ระบบ'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่อทรัพย์สิน'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ราคา'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ซื้อ'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='status',
            field=models.CharField(choices=[('available', 'ว่าง (Available)'), ('in_use', 'กำลังใช้งาน (In-Use)'), ('maintenance', 'ส่งซ่อม (Under Maintenance)'), ('written_off', 'ชำรุด (Written-off)'), ('disposed', 'จำหน่ายแล้ว (Disposed)')], default='available', max_length=20, verbose_name='สถานะ'),
        ),
    ]
