# Generated by Django 5.1.4 on 2026-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0002_masterasset_asset_group_masterasset_asset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterasset',
            name='id_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Code'),
        ),
    ]
