# Generated by Django 5.1.4 on 2026-06-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0003_masterasset_id_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterasset',
            name='asset_group',
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='current_owner',
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='emp_code',
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='location',
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='location_text',
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='section',
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='spec_details',
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='warranty_expire_date',
        ),
        migrations.AddField(
            model_name='masterasset',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='สาขา'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='อาคาร'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ชั้น'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets_images/', verbose_name='รูปภาพ'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='maintenance_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หน่วยช่าง'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='old_asset_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสทรัพย์สินเดิม'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ผู้รับผิดชอบ'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ประกัน'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมวด'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='id_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID CODE'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขเครื่อง'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='status',
            field=models.CharField(choices=[('available', 'ว่าง (Available)'), ('in_use', 'กำลังใช้งาน (In-Use)'), ('maintenance', 'ส่งซ่อม (Under Maintenance)'), ('written_off', 'ชำรุด (Written-off)'), ('disposed', 'จำหน่ายแล้ว (Disposed)')], default='available', max_length=50, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='บริษัท(ขาย)'),
        ),
    ]
