# Generated by Django 5.1.4 on 2026-06-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0004_remove_masterasset_asset_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('pending_it_approval', 'รอ IT อนุมัติ'), ('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังซ่อม'), ('completed', 'ซ่อมเสร็จสิ้น'), ('rejected', 'ไม่อนุมัติ')], default='pending_it_approval', max_length=50),
        ),
    ]
