# Generated by Django 5.1.4 on 2026-06-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0005_alter_maintenancerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterasset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets_system.assetcategory', verbose_name='หมวด'),
        ),
    ]
