# Generated by Django 5.1.4 on 2026-06-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0006_alter_masterasset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventory',
            name='asset_status',
            field=models.CharField(choices=[('normal', 'ปกติ (Normal)'), ('damaged', 'ชำรุด (Damaged)'), ('missing', 'สูญหาย (Missing)')], default='normal', max_length=20, verbose_name='สภาพทรัพย์สิน'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='location_scanned',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สถานที่ตรวจพบ'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
    ]
