# Generated by Django 5.1.4 on 2026-06-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0007_assetinventory_asset_status_and_more'),
        ('branch', '0001_initial'),
        ('sub_branch', '0003_alter_subbranch_sub_branch_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='to_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sub_branch.subbranch', verbose_name='สาขาที่โอนย้ายถึง'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch', verbose_name='บริษัทที่โอนย้ายถึง'),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
