# Generated by Django 5.1.4 on 2026-06-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0008_assettransfer_to_branch_assettransfer_to_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdisposal',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ไม่อนุมัติ'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ไม่อนุมัติ'),
        ),
        migrations.AddField(
            model_name='assetwriteoff',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ไม่อนุมัติ'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ไม่อนุมัติ'),
        ),
    ]
