# Generated by Django 5.1.4 on 2026-06-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0009_assetdisposal_reject_reason_and_more'),
        ('branch', '0001_initial'),
        ('sub_branch', '0003_alter_subbranch_sub_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='from_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from_branch', to='sub_branch.subbranch', verbose_name='สาขาต้นทาง'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='from_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from_company', to='branch.branch', verbose_name='บริษัทต้นทาง'),
        ),
    ]
