# Generated by Django 5.1.4 on 2026-06-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0010_assettransfer_from_branch_assettransfer_from_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterasset',
            name='status',
            field=models.CharField(choices=[('available', 'ปกติ (Normal)'), ('in_use', 'กำลังใช้งาน (In-Use)'), ('maintenance', 'ส่งซ่อม (Under Maintenance)'), ('written_off', 'ชำรุด (Written-off)'), ('disposed', 'จำหน่ายแล้ว (Disposed)')], default='available', max_length=50, verbose_name='สถานะ'),
        ),
    ]
