# Generated by Django 5.1.4 on 2026-06-12 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0011_alter_masterasset_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='destination_head_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_dest_head_approvals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จัดการสาขาปลายทางที่อนุมัติ'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='destination_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_dest_receivers', to=settings.AUTH_USER_MODEL, verbose_name='พนักงานสาขาปลายทางที่รับสินค้า'),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='head_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_head_approvals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จัดการสาขาต้นทางที่อนุมัติ'),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='status',
            field=models.CharField(choices=[('pending_source_head', 'รอหัวหน้าสาขาต้นทางอนุมัติ'), ('pending_destination_receive', 'รอสาขาปลายทางรับสินค้า'), ('pending_destination_head', 'รอหัวหน้าสาขาปลายทางอนุมัติ'), ('pending_accounting', 'รอบัญชีอนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่อนุมัติ')], default='pending_source_head', max_length=50),
        ),
    ]
