# Generated by Django 5.1.4 on 2026-06-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0012_assettransfer_destination_head_approver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterasset',
            name='id_code',
        ),
        migrations.AddField(
            model_name='masterasset',
            name='ax_reason',
            field=models.TextField(blank=True, null=True, verbose_name='AX Reason'),
        ),
        migrations.AddField(
            model_name='masterasset',
            name='ax_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='AX Status'),
        ),
        migrations.AlterField(
            model_name='masterasset',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='หมวด'),
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='masterasset',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ซื้อ'),
        ),
        migrations.RemoveField(
            model_name='masterasset',
            name='warranty',
        ),
        migrations.AddField(
            model_name='masterasset',
            name='warranty',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ประกัน'),
        ),
    ]
