# Generated by Django 5.1.4 on 2026-06-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0013_remove_masterasset_id_code_masterasset_ax_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterasset',
            name='asset_code',
            field=models.CharField(max_length=50, verbose_name='รหัสทรัพย์สิน'),
        ),
    ]
