# Generated by Django 5.1.4 on 2026-07-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0015_assetimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinventory',
            name='asset_status',
            field=models.CharField(choices=[('normal', 'ปกติ (Normal)'), ('damaged_repairable', 'ชำรุด-ซ่อมได้ (Damaged - Repairable)'), ('damaged_unrepairable', 'ชำรุด-ซ่อมไม่ได้ (Damaged - Unrepairable)'), ('missing', 'สูญหาย (Missing)')], default='normal', max_length=20, verbose_name='สภาพทรัพย์สิน'),
        ),
    ]
