# Generated by Django 5.1.4 on 2026-07-01 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0016_alter_assetinventory_asset_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='maintenance_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets_system.maintenancerecord')),
            ],
        ),
    ]
