# Generated by Django 5.1.4 on 2026-07-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_system', '0017_maintenanceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='service_job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Service Job (Ticket)'),
        ),
    ]
