# Generated by Django 5.1.4 on 2025-10-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub_category', '0002_alter_subcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_category.subcategory')),
            ],
            options={
                'db_table': 'base_second_sub_category',
            },
        ),
    ]
