# Generated by Django 5.1.4 on 2025-01-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_iis_staff_alter_members_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='iis_staff',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0),
        ),
    ]
