# Generated by Django 5.1.4 on 2025-01-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_iis_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='iis_staff',
        ),
        migrations.AlterField(
            model_name='members',
            name='is_staff',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
