# Generated by Django 5.1.4 on 2025-01-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_members_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='members',
            name='is_superuser',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0),
        ),
    ]
