# Generated by Django 5.1.4 on 2025-01-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_members_is_active_alter_members_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
