# Generated by Django 5.1.4 on 2025-01-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_members_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=1),
        ),
    ]
