# Generated by Django 5.1.4 on 2025-01-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_members_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_joined',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='members',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
