# Generated by Django 5.1.4 on 2025-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_members_date_joined_alter_members_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_joined',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='members',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
