# Generated by Django 5.1.4 on 2025-01-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_members_date_joined_alter_members_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='last_login',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
