# Generated by Django 5.1.4 on 2025-05-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_members_last_login'),
        ('sub_branch', '0002_rename_branch_name_subbranch_sub_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='sub_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_branch.subbranch'),
        ),
    ]
