# Generated by Django 5.1.4 on 2025-09-15 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_members_sub_branch'),
        ('sub_branch', '0003_alter_subbranch_sub_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='sub_branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_branch.subbranch'),
        ),
    ]
