# Generated by Django 5.1.4 on 2025-09-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('department', '0002_rename_branch_id_department_department_id'),
        ('members', '0015_alter_members_sub_branch'),
        ('sub_branch', '0003_alter_subbranch_sub_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='members',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AlterField(
            model_name='members',
            name='sub_branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sub_branch.subbranch'),
        ),
    ]
