# Generated by Django 5.1.4 on 2026-06-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0002_remove_accessrequest_access_level'),
        ('members', '0016_alter_members_branch_alter_members_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_requests.position'),
        ),
    ]
