# Generated by Django 5.1.4 on 2026-07-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_members_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='module_permissions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
