# Generated by Django 5.1.4 on 2024-12-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='branch_id',
            new_name='department_id',
        ),
    ]
